# Generated by Django 4.0 on 2022-01-17 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_doctormodel_gog_link'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='staff.doctormodel'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staff.doctormodel'),
        ),
        migrations.AlterField(
            model_name='slots',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='staff.doctormodel'),
        ),
    ]
