# Generated by Django 4.0 on 2022-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_bookappointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='is_slot_generated',
            field=models.BooleanField(default=False),
        ),
    ]
