# Generated by Django 4.0 on 2022-01-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_doctorschedule_is_slot_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='conformation_id',
            field=models.CharField(default='err', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='pdf_file',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
