# Generated by Django 4.0 on 2022-01-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_bookappointment_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='conformation_id',
            field=models.CharField(max_length=700, unique=True),
        ),
    ]
