# Generated by Django 4.0 on 2022-01-16 16:05

from django.db import migrations, models
import django.db.models.deletion
import staff.managers


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staff.profile')),
                ('designation', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('fb_link', models.URLField(blank=True)),
                ('tw_link', models.URLField(blank=True)),
                ('gog_link', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'Doctor',
                'ordering': ('created_at',),
            },
            bases=('staff.profile',),
            managers=[
                ('objects', staff.managers.Profilemanager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile/default.png', upload_to='media/profile'),
        ),
    ]
