# Generated by Django 4.0 on 2022-01-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_doctormodel_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='gog_link',
        ),
    ]
